def draw():
    print("- = - = - = - = - = - = - = - = - = - = - = - = - = - = - = -")
    print("|           |           |           |           |           |")
    print("|           |           |           |           |           |")
    print("|           |           |           |           |           |")
    print("|           |           |           |           |           |")
    print("- = - = - = - = - = - = - = - = - = - = - = - = - = - = - = -")
    print("|           |           |           |           |           |")
    print("|           |           |           |           |           |")
    print("|           |           |           |           |           |")
    print("|           |           |           |           |           |")
    print("- = - = - = - = - = - = - = - = - = - = - = - = - = - = - = -")
    print("|           |           |           |           |           |")
    print("|           |           |           |           |           |")
    print("|           |           |           |           |           |")
    print("|           |           |           |           |           |")
    print("- = - = - = - = - = - = - = - = - = - = - = - = - = - = - = -")
    print("|           |           |           |           |           |")
    print("|           |           |           |           |           |")
    print("|           |           |           |           |           |")
    print("|           |           |           |           |           |")
    print("- = - = - = - = - = - = - = - = - = - = - = - = - = - = - = -")
print(draw())


def listmath():
    print("This calculates the product of eight integers.")
    print("Please enter the numbers that you want a product of one by one.")
    u = (int(input("Please enter an integer : ")))
    v = (int(input("Please enter an integer : ")))
    w = (int(input("Please enter an integer : ")))
    x = (int(input("Please enter an integer : ")))
    y = (int(input("Please enter an integer : ")))
    z = (int(input("Please enter an integer : ")))
    r = (int(input("Please enter an integer : ")))
    s = (int(input("Please enter an integer : ")))
    t = (u * v * w * x * y * z * r * s)
    print("The number of your product is "+str(t))

print(listmath())
